language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install unittest2; fi
  - python setup.py install

script:
  - make pep8
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then make flakes; fi
  - make clear_coverage
  - make run_unit_tests
  - make run_integration_tests
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then make run_acceptance_tests; fi

after_success:
  - make coveralls

notifications:
  email:
    on_success: change
    on_failure: change