language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"

install:
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install unittest2; fi
  - python setup.py install

script:
  - make flakes
  - make clear_coverage
  - make run_unit_tests
  - make run_integration_tests
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3.5' ]]; then make run_acceptance_tests; fi

after_success:
  - make coveralls

notifications:
  email:
    on_success: change
    on_failure: change
